// <auto-generated />
using System;
using Alloy.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Alloy.Migrations
{
    [DbContext(typeof(DreesDbContext))]
    partial class DreesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Alloy.DataAccessLayer.AR_AREA", b =>
                {
                    b.Property<int>("AR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AR_CODE")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AR_DIR_NAME")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AR_EN_CD")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AR_EN_NM")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AR_FULL_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("AR_GMAP_CLAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AR_GMAP_CLNG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AR_GMAP_ZOOM")
                        .HasColumnType("int");

                    b.Property<string>("AR_LEAD_CC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AR_LEAD_TO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("AR_MOVE_IN_PAD_DAYS")
                        .HasColumnType("int");

                    b.Property<int?>("AR_OLOC_ID")
                        .HasColumnType("int");

                    b.Property<string>("AR_STATE1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AR_STATE2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AR_STATE3")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AR_STATE4")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AR_ID");

                    b.ToTable("AR_AREA");
                });

            modelBuilder.Entity("Alloy.DataAccessLayer.DSC_DESIGN_CENTER", b =>
                {
                    b.Property<int>("DSC_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AR_ID")
                        .HasColumnType("int");

                    b.Property<bool>("DSC_ACTIVE")
                        .HasColumnType("bit");

                    b.Property<string>("DSC_ADDRESS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_ADDRESS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_DIRECTIONS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_DIRECTIONS1_LBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_DIRECTIONS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_DIRECTIONS2_LBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_DIRECTIONS3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_DIRECTIONS3_LBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_FILENAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_HEADLINE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_HOURS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_HOURS1_LBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_HOURS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_HOURS2_LBL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("DSC_IMAGE")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal?>("DSC_LAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DSC_LNG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DSC_PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_STATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DSC_ZIP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DSC_ID");

                    b.ToTable("DSC_DESIGN_CENTER");
                });
#pragma warning restore 612, 618
        }
    }
}
